container:
  image: golang:latest

#env:
#  GOPROXY: https://proxy.golang.org

deps_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  mod_download_script: go mod download

test_task:
  depends_on:
    - deps
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  lint_script: make lint
  check_script: make check
  always:
    junit_artifacts:
      path: "build/test_results/**/*.xml"
      format: junit

build_task:
  depends_on:
    - deps
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  build_script: |
    make build
